// flow-typed signature: 18a83516bad7e733e47b34315b6b9009
// flow-typed version: <<STUB>>/jwt-simple_v^0.5.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwt-simple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwt-simple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwt-simple/lib/jwt' {
  declare module.exports: any;
}

declare module 'jwt-simple/test/basic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwt-simple/index' {
  declare module.exports: $Exports<'jwt-simple'>;
}
declare module 'jwt-simple/index.js' {
  declare module.exports: $Exports<'jwt-simple'>;
}
declare module 'jwt-simple/lib/jwt.js' {
  declare module.exports: $Exports<'jwt-simple/lib/jwt'>;
}
declare module 'jwt-simple/test/basic.js' {
  declare module.exports: $Exports<'jwt-simple/test/basic'>;
}
