// Auth constants
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';

// Fetch Collections
export const FETCH_COLLECTIONS_REQUEST = 'FETCH_COLLECTIONS_REQUEST';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILED = 'FETCH_COLLECTIONS_FAILED';

// Fetch Single Collection
export const FETCH_COLLECTION_REQUEST = 'FETCH_COLLECTION_REQUEST';
export const FETCH_COLLECTION_SUCCESS = 'FETCH_COLLECTION_SUCCESS';
export const FETCH_COLLECTION_FAILED = 'FETCH_COLLECTION_FAILED';

// Create Collection
export const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILED = 'CREATE_COLLECTION_FAILED';

// Update Collection
export const UPDATE_COLLECTION_REQUEST = 'UPDATE_COLLECTION_REQUEST';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_FAILED = 'UPDATE_COLLECTION_FAILED';

// Delete Collection
export const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_FAILED = 'DELETE_COLLECTION_FAILED';

// Fetch Collection Cards
export const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';

// Create Individual Cards
export const CREATE_CARDS_REQUEST = 'CREATE_CARDS_REQUEST';
export const CREATE_CARDS_SUCCESS = 'CREATE_CARDS_SUCCESS';
export const CREATE_CARDS_FAILED = 'CREATE_CARDS_FAILED';

// Update Individual Cards
export const UPDATE_CARD_REQUEST = 'UPDATE_CARD_REQUEST';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILED = 'UPDATE_CARD_FAILED';

// Delete Individual Cards
export const DELETE_CARD_REQUEST = 'DELETE_CARD_REQUEST';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILED = 'DELETE_CARD_FAILED';

// Current Game
export const GAME_TOGGLE_RESET = 'GAME_TOGGLE_RESET';
export const GAME_SHUFFLE_CARDS = 'GAME_SHUFFLE_CARDS';
export const CARD_FLIP_SIDE = 'CARD_FLIP_SIDE';
export const CARD_TOGGLE_HINT = 'CARD_TOGGLE_HINT';
export const CARD_CHANGE_INDEX = 'CARD_CHANGE_INDEX';
